name: run-router-tests
on: [push]
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install packages
        run: npm install
        working-directory: ./router

      - name: Run Router tests
        run: |
          npx hardhat test
        working-directory: ./router
