name: run-core-tests
on: [push]
jobs:
  run-api-tests:
    env:
      ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
      ZEROX_API_KEY: ${{ secrets.ZEROX_API_KEY }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install packages
        run: npm install
        working-directory: ./core

      - name: Run core tests
        run: |
          npm run test
        working-directory: ./core
